const $ = q => document.querySelector(q);
const $$ = q => [...document.querySelectorAll(q)];

const PARAMS = [
  { key:"distance", label:"対象距離", min:1, max:300, step:1, suffix:"cent", value:70, help:"MIDIからこの距離以内を補正候補にする" },
  { key:"duration", label:"有効持続時間", min:0, max:2000, step:5, suffix:"ms", value:120, help:"ズレが続いた時間で対象を決める" },
  { key:"amount", label:"補正量", min:0, max:100, step:1, suffix:"%", value:80, help:"MIDIへ寄せる割合" },
  { key:"attack", label:"Attack", min:0, max:2000, step:5, suffix:"ms", value:60, help:"補正centが立ち上がる時間" },
  { key:"release", label:"Release", min:0, max:2000, step:5, suffix:"ms", value:120, help:"補正centが0へ戻る時間" },
  { key:"smooth", label:"Smooth", min:0, max:1000, step:5, suffix:"ms", value:40, help:"補正centの細かな変化を均す" },
];
const defaults = () => Object.fromEntries(PARAMS.map(p=>[p.key,p.value]));
const state = {
  ctx:null, audio:null, processed:null, processedWav:null, wavFile:null, midi:[], midiFile:null,
  offsetMs:0, duration:10, zoom:1, waveYZoom:1, pitchYZoom:1, head:0, playing:false, source:null, guideNodes:[],
  startedAt:0, playStart:0, raf:0, mode:"original", guide:false, analysis:null, envelope:null,
  segments:[{id:crypto.randomUUID(),start:0,end:10,settings:defaults()}], currentSegmentId:null,
};

const audioOffset = () => state.offsetMs/1000;
const audioDuration = () => state.audio?.duration || 0;
function timelineDuration(){return Math.max(1,midiDuration(),audioDuration()+Math.max(0,audioOffset()));}
function setStatus(text,ready=false){$("#status span").textContent=text;$("#status").classList.toggle("ready",ready);}
function fmt(sec){sec=Math.max(0,sec);const m=Math.floor(sec/60),s=sec-m*60;return `${String(m).padStart(2,"0")}:${s.toFixed(3).padStart(6,"0")}`;}
function xAt(time){return time/state.duration*$("#timelineStage").clientWidth;}
function timeAt(x){return Math.max(0,Math.min(state.duration,x/$("#timelineStage").clientWidth*state.duration));}
function midiDuration(){return state.midi.reduce((m,n)=>Math.max(m,n.end),0);}
function currentSegment(){
  const local=state.head-audioOffset();
  if(local<0||local>audioDuration())return null;
  let found=state.segments.find((s,i)=>local>=s.start&&(local<s.end||i===state.segments.length-1&&local<=s.end));
  return found||null;
}
function settingsAtLocal(local){return state.segments.find((s,i)=>local>=s.start&&(local<s.end||i===state.segments.length-1&&local<=s.end))?.settings||defaults();}

function buildParams(){
  const grid=$("#knobGrid");grid.innerHTML="";
  for(const p of PARAMS){
    const card=document.createElement("div");card.className="param";card.dataset.key=p.key;
    card.innerHTML=`<div class="param-head"><label>${p.label}</label><output><input class="param-number" type="number" min="${p.min}" max="${p.max}" step="${p.step}"><span>${p.suffix}</span></output></div><input class="param-range" type="range" min="${p.min}" max="${p.max}" step="${p.step}"><small>${p.help}</small>`;
    const change=e=>setParam(p.key,Math.max(p.min,Math.min(p.max,Number(e.target.value))));
    card.querySelector(".param-range").addEventListener("input",change);
    card.querySelector(".param-number").addEventListener("change",change);
    grid.appendChild(card);
  }
  refreshSegmentUI();
}
function setParam(key,value){const seg=currentSegment();if(!seg)return;seg.settings[key]=value;invalidateRender();refreshSegmentUI();if(state.analysis)computeEnvelope();}
function refreshSegmentUI(){
  const seg=currentSegment(),idx=seg?state.segments.indexOf(seg):-1;
  if(seg){$("#settingsTitle").textContent=`区間 ${idx+1}`;$("#segmentRange").textContent=`${(seg.start+audioOffset()).toFixed(3)} – ${(seg.end+audioOffset()).toFixed(3)} sec`;}
  else{$("#settingsTitle").textContent="ボーカル範囲外";$("#segmentRange").textContent="再生ヘッドを波形上へ移動";}
  for(const p of PARAMS){const card=$(`.param[data-key="${p.key}"]`),value=seg?.settings[p.key]??p.value;card.querySelector(".param-range").value=value;card.querySelector(".param-number").value=value;card.querySelectorAll("input").forEach(x=>x.disabled=!seg);}
  state.currentSegmentId=seg?.id||null;renderSegments();
}
function updateCurrentSegment(){const id=currentSegment()?.id||null;if(id!==state.currentSegmentId)refreshSegmentUI();}
function invalidateRender(){state.processed=null;state.processedWav=null;$("#exportBtn").disabled=true;}

function selectedProcessRate(){const value=$("#processRate").value;return value==="auto"?(state.audio?.sampleRate||48000):Number(value);}
function updateEngineReadout(){const source=state.audio?.sampleRate;if(!source){$("#engineReadout").textContent="WAV読込後に表示";return;}const rate=selectedProcessRate(),block=Number($("#blockSize").value),ms=block/rate*1000;$("#engineReadout").textContent=`元 ${(source/1000).toFixed(source%1000?1:0)}kHz → 処理 ${(rate/1000).toFixed(rate%1000?1:0)}kHz / ${block} samples / ${ms.toFixed(1)}ms`;}
async function resampleChannels(channels,fromRate,toRate){if(fromRate===toRate)return channels.map(x=>new Float32Array(x));const length=Math.max(1,Math.round(channels[0].length*toRate/fromRate));const source=new AudioBuffer({length:channels[0].length,numberOfChannels:channels.length,sampleRate:fromRate});channels.forEach((data,ch)=>source.copyToChannel(data,ch));const offline=new OfflineAudioContext(channels.length,length,toRate),node=offline.createBufferSource();node.buffer=source;node.connect(offline.destination);node.start();const rendered=await offline.startRendering();return Array.from({length:rendered.numberOfChannels},(_,ch)=>new Float32Array(rendered.getChannelData(ch)));}
[$("#processRate"),$("#blockSize")].forEach(el=>el.addEventListener("change",()=>{updateEngineReadout();invalidateRender();}));

async function ensureContext(){if(!state.ctx)state.ctx=new AudioContext();if(state.ctx.state==="suspended")await state.ctx.resume();}
$("#wavFile").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;await ensureContext();setStatus("WAVを読み込み中…");try{const data=await file.arrayBuffer();state.audio=await state.ctx.decodeAudioData(data.slice(0));state.wavFile=file;state.offsetMs=0;$("#offset").value=0;$("#offsetOut").textContent="0 ms";state.segments=[{id:crypto.randomUUID(),start:0,end:state.audio.duration,settings:defaults()}];state.head=0;state.analysis=null;invalidateRender();$("#wavName").textContent=`${file.name} · ${state.audio.sampleRate/1000}kHz · ${state.audio.duration.toFixed(2)}s`;updateEngineReadout();mediaChanged();setStatus("WAV読込完了",true);}catch(err){setStatus(`WAVエラー：${err.message}`);}});
$("#midiFile").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;setStatus("MIDIを読み込み中…");try{state.midi=parseMidi(await file.arrayBuffer());state.midiFile=file;state.analysis=null;invalidateRender();$("#midiName").textContent=`${file.name} · ${state.midi.length} notes`;mediaChanged();setStatus("MIDI読込完了",true);}catch(err){setStatus(`MIDIエラー：${err.message}`);}});
function mediaChanged(){state.duration=timelineDuration();updateStage();drawAll();setHead(state.head);$("#analyzeBtn").disabled=!(state.audio&&state.midi.length);$("#renderBtn").disabled=true;}

function parseMidi(buffer){
  const view=new DataView(buffer);let pos=0;const str=n=>{let s="";while(n--)s+=String.fromCharCode(view.getUint8(pos++));return s;};const u32=()=>{const v=view.getUint32(pos);pos+=4;return v;};const u16=()=>{const v=view.getUint16(pos);pos+=2;return v;};const vi=()=>{let v=0,b;do{b=view.getUint8(pos++);v=(v<<7)|(b&127);}while(b&128);return v;};
  if(str(4)!=="MThd")throw new Error("MIDIヘッダーがありません");const hl=u32(),format=u16(),tracks=u16(),division=u16();pos+=hl-6;if(division&0x8000)throw new Error("SMPTE MIDIは未対応です");
  const events=[],tempos=[{tick:0,us:500000}];for(let tr=0;tr<tracks;tr++){if(str(4)!=="MTrk")throw new Error("MIDIトラックが壊れています");const end=pos+u32();let tick=0,status=0;while(pos<end){tick+=vi();let first=view.getUint8(pos++);if(first<0x80)pos--;else status=first;if(status===0xff){const type=view.getUint8(pos++),len=vi();if(type===0x51&&len===3)tempos.push({tick,us:(view.getUint8(pos)<<16)|(view.getUint8(pos+1)<<8)|view.getUint8(pos+2)});pos+=len;continue;}if(status===0xf0||status===0xf7){pos+=vi();continue;}const kind=status&0xf0,channel=status&15,a=view.getUint8(pos++),b=kind===0xc0||kind===0xd0?0:view.getUint8(pos++);if(kind===0x90&&b>0)events.push({tick,type:"on",note:a,velocity:b,channel});else if(kind===0x80||(kind===0x90&&b===0))events.push({tick,type:"off",note:a,channel});}pos=end;}
  tempos.sort((a,b)=>a.tick-b.tick);const uniq=tempos.filter((x,i,a)=>!i||x.tick!==a[i-1].tick);let sec=0,last=0,us=500000;for(const t of uniq){sec+=(t.tick-last)*us/1e6/division;t.sec=sec;last=t.tick;us=t.us;}const tickSec=tick=>{let t=uniq[0];for(const x of uniq){if(x.tick>tick)break;t=x;}return t.sec+(tick-t.tick)*t.us/1e6/division;};events.sort((a,b)=>a.tick-b.tick||(a.type==="off"?-1:1));const active=new Map(),notes=[];for(const e of events){const key=`${e.channel}:${e.note}`;if(e.type==="on")active.set(key,e);else if(active.has(key)){const s=active.get(key);notes.push({note:e.note,start:tickSec(s.tick),end:tickSec(e.tick),velocity:s.velocity});active.delete(key);}}return notes.filter(n=>n.end>n.start).sort((a,b)=>a.start-b.start);
}

function updateStage(){state.duration=timelineDuration();const width=Math.max(900,Math.round($("#timelineScroll").clientWidth*state.zoom));$("#timelineStage").style.width=`${width}px`;for(const c of [$("#waveCanvas"),$("#pitchCanvas")]){c.width=width*devicePixelRatio;c.style.width=`${width}px`;}drawRuler();renderSegments();positionHead();}
function drawRuler(){const r=$("#ruler");r.innerHTML="";const step=state.duration>180?30:state.duration>60?10:state.duration>20?5:1;for(let t=0;t<=state.duration;t+=step){const s=document.createElement("span");s.style.left=`${xAt(t)}px`;s.textContent=t<60?`${t}s`:`${Math.floor(t/60)}:${String(t%60).padStart(2,"0")}`;r.appendChild(s);}}
function cc(canvas){const c=canvas.getContext("2d");c.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);c.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);return c;}
function drawWave(){const canvas=$("#waveCanvas"),ctx=cc(canvas),w=canvas.clientWidth,h=canvas.clientHeight;if(!state.audio){ctx.fillStyle="#596274";ctx.fillText("VOCAL WAVを読み込んでください",45,66);return;}const data=state.audio.getChannelData(0);ctx.strokeStyle="#91a0b8";ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<w;x++){const timeline=timeAt(x),local=timeline-audioOffset();if(local<0||local>=state.audio.duration)continue;const center=Math.floor(local*state.audio.sampleRate),radius=Math.max(1,Math.ceil(state.audio.length/w/state.zoom));let lo=1,hi=-1;for(let i=Math.max(0,center-radius);i<Math.min(data.length,center+radius);i++){lo=Math.min(lo,data[i]);hi=Math.max(hi,data[i]);}ctx.moveTo(x,h/2+lo*h*.42*state.waveYZoom);ctx.lineTo(x,h/2+hi*h*.42*state.waveYZoom);}ctx.stroke();ctx.fillStyle="rgba(184,255,61,.75)";ctx.fillText(`左右ドラッグ：位置移動　縦ピンチ：${state.waveYZoom.toFixed(1)}×`,12,h-10);}
function noteRange(){if(!state.midi.length)return[48,72];let baseLo=Math.min(...state.midi.map(n=>n.note))-2,baseHi=Math.max(...state.midi.map(n=>n.note))+2,center=(baseLo+baseHi)/2,span=Math.max(6,(baseHi-baseLo)/state.pitchYZoom);return[Math.max(0,center-span/2),Math.min(127,center+span/2)];}
function drawPitch(){const canvas=$("#pitchCanvas"),ctx=cc(canvas),w=canvas.clientWidth,h=canvas.clientHeight,[lo,hi]=noteRange(),y=n=>h-(n-lo)/(hi-lo)*h;ctx.strokeStyle="#1d242e";ctx.fillStyle="#566071";ctx.font="9px sans-serif";for(let n=Math.ceil(lo);n<=hi;n++){const yy=y(n);ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke();if(n%12===0)ctx.fillText(`C${Math.floor(n/12)-1}`,5,yy-3);}for(const n of state.midi){const x=xAt(n.start),ww=Math.max(2,xAt(n.end)-xAt(n.start));ctx.fillStyle="rgba(131,232,255,.28)";ctx.strokeStyle="rgba(131,232,255,.75)";ctx.fillRect(x,y(n.note+.45),ww,y(n.note-.45)-y(n.note+.45));ctx.strokeRect(x,y(n.note+.45),ww,y(n.note-.45)-y(n.note+.45));}if(!state.analysis)return;const {times,pitches,status}=state.analysis;ctx.lineWidth=1.5;let color="",open=false;for(let i=0;i<times.length;i++){if(!pitches[i]){if(open){ctx.stroke();open=false;}continue;}const c=status?.[i]==="target"?"#b8ff3d":status?.[i]==="short"?"#ffc857":status?.[i]==="far"?"#ff647c":"#70798a",xx=xAt(times[i]+audioOffset()),yy=y(69+12*Math.log2(pitches[i]/440));if(c!==color){if(open)ctx.stroke();ctx.beginPath();ctx.strokeStyle=c;color=c;open=false;}if(!open){ctx.moveTo(xx,yy);open=true;}else ctx.lineTo(xx,yy);}if(open)ctx.stroke();}
function drawAll(){drawWave();drawPitch();}

function setOffset(ms){if(state.playing)stop();state.offsetMs=Math.max(-300000,Math.min(300000,Math.round(ms)));$("#offset").value=state.offsetMs;$("#offsetOut").textContent=`${state.offsetMs} ms`;state.duration=timelineDuration();invalidateRender();updateStage();drawAll();refreshSegmentUI();if(state.analysis)computeEnvelope();}
$("#offset").addEventListener("input",e=>setOffset(Number(e.target.value)));$$('[data-nudge]').forEach(b=>b.addEventListener("click",()=>setOffset(state.offsetMs+Number(b.dataset.nudge))));$("#offsetReset").addEventListener("click",()=>setOffset(0));

let waveDrag=null;
$("#waveCanvas").addEventListener("pointerdown",e=>{if(e.pointerType==="touch")return;e.preventDefault();waveDrag={x:e.clientX,offset:state.offsetMs,moved:false};const move=ev=>{const dx=ev.clientX-waveDrag.x;if(Math.abs(dx)>2)waveDrag.moved=true;const dt=dx/$("#timelineStage").clientWidth*state.duration*1000;setOffset(waveDrag.offset+dt);};const up=ev=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);if(!waveDrag.moved){const r=$("#waveCanvas").getBoundingClientRect();setHead(timeAt(ev.clientX-r.left));}waveDrag=null;};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);});
$("#pitchCanvas").addEventListener("pointerdown",e=>{if(e.pointerType==="touch")return;const r=e.currentTarget.getBoundingClientRect();setHead(timeAt(e.clientX-r.left));});
function enableVerticalPinch(canvas,key,redraw){const touches=new Map();let startDistance=0,startZoom=1;canvas.addEventListener("pointerdown",e=>{if(e.pointerType!=="touch")return;e.preventDefault();canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,e);if(touches.size===2){const [a,b]=[...touches.values()];startDistance=Math.abs(a.clientY-b.clientY)||1;startZoom=state[key];}});canvas.addEventListener("pointermove",e=>{if(!touches.has(e.pointerId))return;e.preventDefault();touches.set(e.pointerId,e);if(touches.size===2){const [a,b]=[...touches.values()],distance=Math.abs(a.clientY-b.clientY)||1;state[key]=Math.max(.5,Math.min(8,startZoom*distance/startDistance));redraw();}});const end=e=>touches.delete(e.pointerId);canvas.addEventListener("pointerup",end);canvas.addEventListener("pointercancel",end);}
enableVerticalPinch($("#waveCanvas"),"waveYZoom",drawWave);
enableVerticalPinch($("#pitchCanvas"),"pitchYZoom",drawPitch);
$("#ruler").addEventListener("pointerdown",e=>{const r=e.currentTarget.getBoundingClientRect();setHead(timeAt(e.clientX-r.left));});
$("#playhead").addEventListener("pointerdown",e=>{e.preventDefault();const move=ev=>{const r=$("#timelineStage").getBoundingClientRect();setHead(timeAt(ev.clientX-r.left));};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);});
function setHead(time){if(state.playing)stop();state.head=Math.max(0,Math.min(state.duration,Number(time)||0));$("#headTime").value=state.head.toFixed(3);$("#timeDisplay").textContent=fmt(state.head);positionHead();updateCurrentSegment();}
function positionHead(){$("#playhead").style.display="block";$("#playhead").style.left=`${xAt(state.head)}px`;}
$("#headTime").addEventListener("change",e=>setHead(e.target.value));

function renderSegments(){const lane=$("#regionLane");lane.innerHTML="";const current=currentSegment();state.segments.forEach((s,i)=>{const el=document.createElement("div");el.className=`region-block${current?.id===s.id?" current":""}`;el.style.left=`${xAt(s.start+audioOffset())}px`;el.style.width=`${Math.max(2,xAt(s.end)-xAt(s.start))}px`;el.innerHTML=`<span>区間 ${i+1}</span>`;el.addEventListener("click",()=>setHead(Math.max(0,s.start+audioOffset()+.001)));lane.appendChild(el);});}
$("#splitBtn").addEventListener("click",()=>{const local=state.head-audioOffset(),idx=state.segments.findIndex(s=>local>s.start+.01&&local<s.end-.01);if(idx<0)return;const src=state.segments[idx],left={id:crypto.randomUUID(),start:src.start,end:local,settings:{...src.settings}},right={id:crypto.randomUUID(),start:local,end:src.end,settings:{...src.settings}};state.segments.splice(idx,1,left,right);invalidateRender();renderSegments();refreshSegmentUI();if(state.analysis)computeEnvelope();});
$("#mergePrevBtn").addEventListener("click",()=>{const seg=currentSegment(),idx=state.segments.indexOf(seg);if(idx<=0)return;const prev=state.segments[idx-1],merged={id:crypto.randomUUID(),start:prev.start,end:seg.end,settings:{...seg.settings}};state.segments.splice(idx-1,2,merged);invalidateRender();renderSegments();refreshSegmentUI();if(state.analysis)computeEnvelope();});

function targetNoteAtLocal(local){const timeline=local+audioOffset();let chosen=null;for(const n of state.midi)if(n.start<=timeline&&timeline<=n.end&&(!chosen||n.velocity>chosen.velocity))chosen=n;return chosen;}
$("#analyzeBtn").addEventListener("click",async()=>{await ensureContext();setStatus("ピッチを解析中…");showProgress(0,"ピッチ解析中…");const mono=new Float32Array(state.audio.length);for(let ch=0;ch<state.audio.numberOfChannels;ch++){const d=state.audio.getChannelData(ch);for(let i=0;i<d.length;i++)mono[i]+=d[i]/state.audio.numberOfChannels;}const worker=new Worker("./analysis-worker.js");worker.onmessage=e=>{state.analysis=e.data;worker.terminate();computeEnvelope();$("#renderBtn").disabled=false;hideProgress();setStatus("解析完了",true);};worker.postMessage({samples:mono,sampleRate:state.audio.sampleRate},[mono.buffer]);});
const centDiff=(measured,target)=>1200*Math.log2(measured/target);
function computeEnvelope(){if(!state.analysis)return;const {times,pitches}=state.analysis,status=new Array(times.length).fill("none"),raw=new Float32Array(times.length),eligible=new Array(times.length).fill(false),noteIds=new Array(times.length).fill("");for(let i=0;i<times.length;i++){const target=targetNoteAtLocal(times[i]),f=pitches[i],cfg=settingsAtLocal(times[i]);if(!target||!f){status[i]="none";continue;}const error=centDiff(f,440*Math.pow(2,(target.note-69)/12));raw[i]=-error*cfg.amount/100;noteIds[i]=`${target.start}:${target.note}`;if(Math.abs(error)<=cfg.distance){eligible[i]=true;status[i]="short";}else status[i]="far";}
  let i=0;const groups=[];while(i<times.length){if(!eligible[i]){i++;continue;}let j=i+1;while(j<times.length&&eligible[j]&&noteIds[j]===noteIds[i]&&settingsAtLocal(times[j])===settingsAtLocal(times[i]))j++;const cfg=settingsAtLocal(times[i]),dur=(times[j-1]-times[i])*1000+20;if(dur>=cfg.duration){for(let k=i;k<j;k++)status[k]="target";groups.push({a:i,b:j-1});}i=j;}
  const values=new Float32Array(times.length);for(const g of groups)for(let k=g.a;k<=g.b;k++){const cfg=settingsAtLocal(times[k]),from=(times[k]-times[g.a])*1000,to=(times[g.b]-times[k])*1000,a=cfg.attack?Math.min(1,from/cfg.attack):1,r=cfg.release?Math.min(1,to/cfg.release):1;values[k]=raw[k]*Math.min(a,r);}const smooth=new Float32Array(values.length);for(let k=0;k<values.length;k++){const radius=Math.round(settingsAtLocal(times[k]).smooth/20/2);let sum=0,count=0;for(let q=Math.max(0,k-radius);q<=Math.min(values.length-1,k+radius);q++){sum+=values[q];count++;}smooth[k]=sum/Math.max(1,count);}state.analysis.status=status;state.envelope={stepSec:times.length>1?times[1]-times[0]:.02,values:smooth};invalidateRender();const frames=status.filter(x=>x==="target").length;$("#targetCount").textContent=groups.length;$("#targetTime").textContent=`${(frames*state.envelope.stepSec).toFixed(2)}s`;let max=0;for(const v of smooth)max=Math.max(max,Math.abs(v));$("#maxCorrection").textContent=`${max.toFixed(0)}¢`;drawPitch();}

$("#renderBtn").addEventListener("click",async()=>{if(!state.envelope)return;setStatus("音声エンジンを準備中…");showProgress(0,"音声エンジンを準備中…");$("#renderBtn").disabled=true;const originalRate=state.audio.sampleRate,processRate=selectedProcessRate(),blockSize=Number($("#blockSize").value);let channels=[];for(let ch=0;ch<state.audio.numberOfChannels;ch++)channels.push(new Float32Array(state.audio.getChannelData(ch)));channels=await resampleChannels(channels,originalRate,processRate);const worker=new Worker("./rubberband-worker.js");let responded=false;const watchdog=setTimeout(()=>{if(responded)return;worker.terminate();$("#renderBtn").disabled=false;hideProgress();setStatus("音声エンジンが起動できませんでした");alert("音声エンジンの起動が15秒以内に完了しませんでした。start.commandから起動しているか確認してください。");},15000);const fail=message=>{clearTimeout(watchdog);worker.terminate();$("#renderBtn").disabled=false;hideProgress();setStatus(`プレビュー生成エラー：${message}`);alert(`プレビューを生成できませんでした。\n${message}`);};worker.onerror=e=>fail(e.message||"Workerの起動に失敗しました");worker.onmessage=async e=>{responded=true;clearTimeout(watchdog);if(e.data.error){fail(e.data.error);return;}if("progress"in e.data)showProgress(e.data.progress,e.data.text||"全編を補正中…");if(e.data.done){let channelBuffers=e.data.channelBuffers;channelBuffers=await resampleChannels(channelBuffers,processRate,originalRate);state.processed=state.ctx.createBuffer(channelBuffers.length,channelBuffers[0].length,originalRate);channelBuffers.forEach((b,i)=>state.processed.copyToChannel(b,i));state.processedWav=encodeAlignedWav(channelBuffers,originalRate);worker.terminate();$("#renderBtn").disabled=false;$("#exportBtn").disabled=false;hideProgress();setStatus("補正プレビュー生成完了",true);state.mode="processed";refreshAudition();}};worker.postMessage({channelBuffers:channels,sampleRate:processRate,blockSize,envelope:{stepSec:state.envelope.stepSec,values:state.envelope.values}},channels.map(x=>x.buffer));});
function encodeAlignedWav(channels,sr){const offset=Math.round(audioOffset()*sr),length=Math.max(1,Math.round(state.duration*sr)),aligned=channels.map(()=>new Float32Array(length));for(let ch=0;ch<channels.length;ch++){const srcStart=Math.max(0,-offset),dstStart=Math.max(0,offset),count=Math.min(channels[ch].length-srcStart,length-dstStart);if(count>0)aligned[ch].set(channels[ch].subarray(srcStart,srcStart+count),dstStart);}const bytes=3,frames=length,buffer=new ArrayBuffer(44+frames*channels.length*bytes),v=new DataView(buffer),text=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));text(0,"RIFF");v.setUint32(4,36+frames*channels.length*bytes,true);text(8,"WAVE");text(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels.length,true);v.setUint32(24,sr,true);v.setUint32(28,sr*channels.length*bytes,true);v.setUint16(32,channels.length*bytes,true);v.setUint16(34,24,true);text(36,"data");v.setUint32(40,frames*channels.length*bytes,true);let o=44;for(let i=0;i<frames;i++)for(let ch=0;ch<aligned.length;ch++){let n=Math.round(Math.max(-1,Math.min(1,aligned[ch][i]))*8388607);if(n<0)n+=16777216;v.setUint8(o++,n&255);v.setUint8(o++,(n>>8)&255);v.setUint8(o++,(n>>16)&255);}return buffer;}
function showProgress(p,text){$("#progressWrap").classList.remove("hidden");$("#progressBar").style.width=`${Math.round(p*100)}%`;$("#progressText").textContent=`${text} ${Math.round(p*100)}%`;}
function hideProgress(){$("#progressWrap").classList.add("hidden");}
$("#exportBtn").addEventListener("click",()=>{if(!state.processedWav)return;const blob=new Blob([state.processedWav],{type:"audio/wav"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${state.wavFile?.name.replace(/\.wav$/i,"")||"vocal"}_VECTOR_PITCH.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});

function stop(){if(state.source){try{state.source.stop();}catch{}state.source=null;}state.guideNodes.forEach(n=>{try{n.stop();}catch{}});state.guideNodes=[];cancelAnimationFrame(state.raf);state.playing=false;$("#playBtn").textContent="▶";$("#playBtn").classList.remove("playing");}
async function togglePlay(){if(state.playing){stop();return;}await ensureContext();const buffer=state.mode==="processed"&&state.processed?state.processed:state.audio;if(!buffer)return;if(state.head>=state.duration-.001)state.head=0;state.playing=true;state.playStart=state.head;state.startedAt=state.ctx.currentTime;$("#playBtn").textContent="■";$("#playBtn").classList.add("playing");const startTimeline=state.head,aStart=audioOffset(),delay=Math.max(0,aStart-startTimeline),bufferOffset=Math.max(0,startTimeline-aStart);if(bufferOffset<buffer.duration){state.source=state.ctx.createBufferSource();state.source.buffer=buffer;state.source.connect(state.ctx.destination);state.source.start(state.ctx.currentTime+delay,bufferOffset);}if(state.guide)playGuide(startTimeline);tick();}
function playGuide(start){const now=state.ctx.currentTime;for(const n of state.midi){if(n.end<start)continue;const osc=state.ctx.createOscillator(),gain=state.ctx.createGain();osc.frequency.value=440*Math.pow(2,(n.note-69)/12);gain.gain.value=.055;osc.connect(gain).connect(state.ctx.destination);const a=now+Math.max(0,n.start-start),b=now+Math.max(.01,n.end-start);osc.start(a);osc.stop(b);state.guideNodes.push(osc);}}
function tick(){if(!state.playing)return;const t=state.playStart+(state.ctx.currentTime-state.startedAt);if(t>=state.duration){stop();setHead(state.duration);return;}state.head=t;$("#headTime").value=t.toFixed(3);$("#timeDisplay").textContent=fmt(t);positionHead();updateCurrentSegment();state.raf=requestAnimationFrame(tick);}
$("#playBtn").addEventListener("click",togglePlay);window.addEventListener("keydown",e=>{if(e.code!=="Space"||["INPUT","TEXTAREA"].includes(document.activeElement?.tagName))return;e.preventDefault();togglePlay();});
$$('.audition-tabs button').forEach(b=>b.addEventListener("click",()=>{if(b.dataset.mode==="guide")state.guide=!state.guide;else state.mode=b.dataset.mode;refreshAudition();}));
function refreshAudition(){$$('.audition-tabs button').forEach(b=>b.classList.toggle("active",b.dataset.mode==="guide"?state.guide:b.dataset.mode===state.mode));}
$("#zoom").addEventListener("input",e=>{state.zoom=Number(e.target.value);updateStage();drawAll();});window.addEventListener("resize",()=>{updateStage();drawAll();});

buildParams();updateStage();drawAll();setHead(0);
